x-common-env: &common_env
  REDIS_URL: redis://redis:6379/0
  TEMP_DIR: /tmp/hachimi_ai_mad
  PUBLISH_DIR: /tmp/hachimi_ai_mad/publish

x-common-volumes: &common_volumes
  - ./data/tmp:/tmp/hachimi_ai_mad
  - ./data/publish:/tmp/hachimi_ai_mad/publish

services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    build: .
    env_file: .env
    environment:
      <<: *common_env
    volumes: *common_volumes
    ports: ["8000:8000"]
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    command: ["uvicorn","app.main:app","--host","0.0.0.0","--port","8000"]

  worker:
    build: .
    env_file: .env
    environment:
      <<: *common_env
      CELERY_EAGER: "0"
    volumes: *common_volumes
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    command: ["celery","-A","app.workers.celery_app:celery_app","worker","--loglevel=INFO"]

