version: "3.9"
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

  api:
    build: .
    depends_on: [redis]
    env_file: .env
    environment:
      # 覆盖默认，确保容器内也能访问 redis 服务名
      REDIS_URL: "redis://redis:6379/0"
      TEMP_DIR: "/tmp/hachimi_ai_mad"
      PUBLISH_DIR: "/tmp/hachimi_publish"
    volumes:
      - ./data/tmp:/tmp/hachimi_ai_mad
      - ./data/publish:/tmp/hachimi_publish
    ports:
      - "8000:8000"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

  worker:
    build: .
    depends_on: [redis]
    env_file: .env
    environment:
      REDIS_URL: "redis://redis:6379/0"
      TEMP_DIR: "/tmp/hachimi_ai_mad"
      PUBLISH_DIR: "/tmp/hachimi_publish"
      # 本地开发：若想看 API 轮询进度，建议把 CELERY_EAGER 设为 0
      CELERY_EAGER: "0"
    volumes:
      - ./data/tmp:/tmp/hachimi_ai_mad
      - ./data/publish:/tmp/hachimi_publish
    command: ["celery", "-A", "app.workers.celery_app:celery_app", "worker", "--loglevel=INFO"]
